version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - redis
