apiVersion: v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: mzq
spec:
  ingressClassName: nginx
  rules:
    - host: www.web.com
      http:
        paths:
          - backend:
              service:
                name: web-service
                port:
                  number: 8081
            path: /
            pathType: Prefix
    - host: www.redis.com
      http:
        paths:
          - backend:
              service:
                name: redis-service
                port:
                  number: 8081
            path: /
            pathType: Prefix